<?php

namespace Database\Seeders;

use App\Models\Attribute;
use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AttributeTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        DB::statement('SET FOREIGN_KEY_CHECKS=0;');

        DB::table('attributes')->truncate();
        DB::table('attribute_translations')->truncate();

        $now = Carbon::now();

        $attributes = [
            [
                'id'                => '1',
                'code'                => 'sku',
                'name'                => 'SKU',
                'type'                => 'text',
                'validation'          => NULL,
                'position'            => '1',
                'is_required'         => '1',
                'is_unique'           => '1',
                'value_per_locale'    => '0',
                'value_per_channel'   => '0',
                'is_filterable'       => '0',
                'is_configurable'     => '0',
                'is_user_defined'     => '0',
                'is_visible_on_front' => '0',
                'use_in_flat'         => '1',
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => '0',
            ],
            [
                'id'                => '2',
                'code'                => 'name',
                'name'                => 'Name',
                'type'                => 'text',
                'validation'          => NULL,
                'position'            => '3',
                'is_required'         => '1',
                'is_unique'           => '0',
                'value_per_locale'    => '1',
                'value_per_channel'   => '1',
                'is_filterable'       => '0',
                'is_configurable'     => '0',
                'is_user_defined'     => '0',
                'is_visible_on_front' => '0',
                'use_in_flat'         => '1',
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => '1',
            ],
            [
                'id'                => '3',
                'code'                => 'url_key',
                'name'          => 'URL Key',
                'type'                => 'text',
                'validation'          => NULL,
                'position'            => '4',
                'is_required'         => '1',
                'is_unique'           => '1',
                'value_per_locale'    => '0',
                'value_per_channel'   => '0',
                'is_filterable'       => '0',
                'is_configurable'     => '0',
                'is_user_defined'     => '0',
                'is_visible_on_front' => '0',
                'use_in_flat'         => '1',
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => '0',
            ],
            [
                'id'                => '4',
                'code'                => 'tax_category_id',
                'name'          => 'Tax Category',
                'type'                => 'select',
                'validation'          => NULL,
                'position'            => '5',
                'is_required'         => '0',
                'is_unique'           => '0',
                'value_per_locale'    => '0',
                'value_per_channel'   => '1',
                'is_filterable'       => '0',
                'is_configurable'     => '0',
                'is_user_defined'     => '0',
                'is_visible_on_front' => '0',
                'use_in_flat'         => '1',
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => '0',
            ],
            [
                'id'                => '5',
                'code'                => 'new',
                'name'          => 'New',
                'type'                => 'boolean',
                'validation'          => NULL,
                'position'            => '6',
                'is_required'         => '0',
                'is_unique'           => '0',
                'value_per_locale'    => '0',
                'value_per_channel'   => '0',
                'is_filterable'       => '0',
                'is_configurable'     => '0',
                'is_user_defined'     => '0',
                'is_visible_on_front' => '0',
                'use_in_flat'         => '1',
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => '0',
            ],
            [
                'id'                => '6',
                'code'                => 'featured',
                'name'          => 'Featured',
                'type'                => 'boolean',
                'validation'          => NULL,
                'position'            => '7',
                'is_required'         => '0',
                'is_unique'           => '0',
                'value_per_locale'    => '0',
                'value_per_channel'   => '0',
                'is_filterable'       => '0',
                'is_configurable'     => '0',
                'is_user_defined'     => '0',
                'is_visible_on_front' => '0',
                'use_in_flat'         => '1',
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => '0',
            ],
            [
                'id'                => '7',
                'code'                => 'visible_individually',
                'name'          => 'Visible Individually',
                'type'                => 'boolean',
                'validation'          => NULL,
                'position'            => '9',
                'is_required'         => '1',
                'is_unique'           => '0',
                'value_per_locale'    => '0',
                'value_per_channel'   => '0',
                'is_filterable'       => '0',
                'is_configurable'     => '0',
                'is_user_defined'     => '0',
                'is_visible_on_front' => '0',
                'created_at'          => $now,
                'use_in_flat'         => '1',
                'updated_at'          => $now,
                'is_comparable'       => '0',
            ],
            [
                'id'                => '8',
                'code'                => 'status',
                'name'          => 'Status',
                'type'                => 'boolean',
                'validation'          => NULL,
                'position'            => '10',
                'is_required'         => '1',
                'is_unique'           => '0',
                'value_per_locale'    => '0',
                'value_per_channel'   => '0',
                'is_filterable'       => '0',
                'is_configurable'     => '0',
                'is_user_defined'     => '0',
                'is_visible_on_front' => '0',
                'use_in_flat'         => '1',
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => '0',
            ],
            [
                'id'                => '9',
                'code'                => 'short_description',
                'name'          => 'Short Description',
                'type'                => 'textarea',
                'validation'          => NULL,
                'position'            => '11',
                'is_required'         => '1',
                'is_unique'           => '0',
                'value_per_locale'    => '1',
                'value_per_channel'   => '1',
                'is_filterable'       => '0',
                'is_configurable'     => '0',
                'is_user_defined'     => '0',
                'is_visible_on_front' => '0',
                'use_in_flat'         => '1',
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => '0',
            ],
            [
                'id'                => '10',
                'code'                => 'description',
                'name'          => 'Description',
                'type'                => 'textarea',
                'validation'          => NULL,
                'position'            => '12',
                'is_required'         => '1',
                'is_unique'           => '0',
                'value_per_locale'    => '1',
                'value_per_channel'   => '1',
                'is_filterable'       => '0',
                'is_configurable'     => '0',
                'is_user_defined'     => '0',
                'is_visible_on_front' => '0',
                'use_in_flat'         => '1',
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => '1',
            ],
            [
                'id'                => '11',
                'code'                => 'price',
                'name'          => 'Price',
                'type'                => 'price',
                'validation'          => 'decimal',
                'position'            => '13',
                'is_required'         => '1',
                'is_unique'           => '0',
                'value_per_locale'    => '0',
                'value_per_channel'   => '0',
                'is_filterable'       => '1',
                'is_configurable'     => '0',
                'is_user_defined'     => '0',
                'is_visible_on_front' => '0',
                'use_in_flat'         => '1',
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => '1',
            ],
            [
                'id'                => '12',
                'code'                => 'cost',
                'name'          => 'Cost',
                'type'                => 'price',
                'validation'          => 'decimal',
                'position'            => '14',
                'is_required'         => '0',
                'is_unique'           => '0',
                'value_per_locale'    => '0',
                'value_per_channel'   => '1',
                'is_filterable'       => '0',
                'is_configurable'     => '0',
                'is_user_defined'     => '1',
                'is_visible_on_front' => '0',
                'use_in_flat'         => '1',
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => '0',
            ],
            [
                'id'                => '13',
                'code'                => 'special_price',
                'name'          => 'Special Price',
                'type'                => 'price',
                'validation'          => 'decimal',
                'position'            => '15',
                'is_required'         => '0',
                'is_unique'           => '0',
                'value_per_locale'    => '0',
                'value_per_channel'   => '0',
                'is_filterable'       => '0',
                'is_configurable'     => '0',
                'is_user_defined'     => '0',
                'is_visible_on_front' => '0',
                'use_in_flat'         => '1',
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => '0',
            ],
            [
                'id'                => '14',
                'code'                => 'special_price_from',
                'name'          => 'Special Price From',
                'type'                => 'date',
                'validation'          => NULL,
                'position'            => '16',
                'is_required'         => '0',
                'is_unique'           => '0',
                'value_per_locale'    => '0',
                'value_per_channel'   => '1',
                'is_filterable'       => '0',
                'is_configurable'     => '0',
                'is_user_defined'     => '0',
                'is_visible_on_front' => '0',
                'use_in_flat'         => '1',
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => '0',
            ],
            [
                'id'                => '15',
                'code'                => 'special_price_to',
                'name'          => 'Special Price To',
                'type'                => 'date',
                'validation'          => NULL,
                'position'            => '17',
                'is_required'         => '0',
                'is_unique'           => '0',
                'value_per_locale'    => '0',
                'value_per_channel'   => '1',
                'is_filterable'       => '0',
                'is_configurable'     => '0',
                'is_user_defined'     => '0',
                'use_in_flat'         => '1',
                'is_visible_on_front' => '0',
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => '0',
            ],
            [
                'id'                => '16',
                'code'                => 'meta_title',
                'name'          => 'Meta Title',
                'type'                => 'textarea',
                'validation'          => NULL,
                'position'            => '18',
                'is_required'         => '0',
                'is_unique'           => '0',
                'value_per_locale'    => '1',
                'value_per_channel'   => '1',
                'is_filterable'       => '0',
                'is_configurable'     => '0',
                'is_user_defined'     => '0',
                'is_visible_on_front' => '0',
                'use_in_flat'         => '1',
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => '0',
            ],
            [
                'id'                => '17',
                'code'                => 'meta_keywords',
                'name'          => 'Meta Keywords',
                'type'                => 'textarea',
                'validation'          => NULL,
                'position'            => '20',
                'is_required'         => '0',
                'is_unique'           => '0',
                'value_per_locale'    => '1',
                'value_per_channel'   => '1',
                'is_filterable'       => '0',
                'is_configurable'     => '0',
                'is_user_defined'     => '0',
                'is_visible_on_front' => '0',
                'use_in_flat'         => '1',
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => '0',
            ],
            [
                'id'                => '18',
                'code'                => 'meta_description',
                'name'          => 'Meta Description',
                'type'                => 'textarea',
                'validation'          => NULL,
                'position'            => '21',
                'is_required'         => '0',
                'is_unique'           => '0',
                'value_per_locale'    => '1',
                'value_per_channel'   => '1',
                'is_filterable'       => '0',
                'is_configurable'     => '0',
                'is_user_defined'     => '1',
                'is_visible_on_front' => '0',
                'use_in_flat'         => '1',
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => '0',
            ],
            [
                'id'                => '19',
                'code'                => 'length',
                'name'          => 'Length',
                'type'                => 'text',
                'validation'          => 'decimal',
                'position'            => '22',
                'is_required'         => '0',
                'is_unique'           => '0',
                'value_per_locale'    => '0',
                'value_per_channel'   => '0',
                'is_filterable'       => '0',
                'is_configurable'     => '0',
                'is_user_defined'     => '1',
                'is_visible_on_front' => '0',
                'use_in_flat'         => '1',
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => '0',
            ],
            [
                'id'                => '20',
                'code'                => 'width',
                'name'          => 'Width',
                'type'                => 'text',
                'validation'          => 'decimal',
                'position'            => '23',
                'is_required'         => '0',
                'is_unique'           => '0',
                'value_per_locale'    => '0',
                'value_per_channel'   => '0',
                'is_filterable'       => '0',
                'is_configurable'     => '0',
                'is_user_defined'     => '1',
                'is_visible_on_front' => '0',
                'use_in_flat'         => '1',
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => '0',
            ],
            [
                'id'                => '21',
                'code'                => 'height',
                'name'          => 'Height',
                'type'                => 'text',
                'validation'          => 'decimal',
                'position'            => '24',
                'is_required'         => '0',
                'is_unique'           => '0',
                'value_per_locale'    => '0',
                'value_per_channel'   => '0',
                'is_filterable'       => '0',
                'is_configurable'     => '0',
                'is_user_defined'     => '1',
                'is_visible_on_front' => '0',
                'use_in_flat'         => '1',
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => '0',
            ],
            [
                'id'                => '22',
                'code'                => 'weight',
                'name'          => 'Weight',
                'type'                => 'text',
                'validation'          => 'decimal',
                'position'            => '25',
                'is_required'         => '0',
                'is_unique'           => '0',
                'value_per_locale'    => '0',
                'value_per_channel'   => '0',
                'is_filterable'       => '0',
                'is_configurable'     => '0',
                'is_user_defined'     => '0',
                'is_visible_on_front' => '0',
                'use_in_flat'         => '1',
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => '0',
            ],
            [
                'id'                => '23',
                'code'                => 'color',
                'name'          => 'Color',
                'type'                => 'select',
                'validation'          => NULL,
                'position'            => '26',
                'is_required'         => '0',
                'is_unique'           => '0',
                'value_per_locale'    => '0',
                'value_per_channel'   => '0',
                'is_filterable'       => '1',
                'is_configurable'     => '1',
                'is_user_defined'     => '1',
                'is_visible_on_front' => '0',
                'use_in_flat'         => '1',
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => '0',
            ],
            [
                'id'                => '24',
                'code'                => 'size',
                'name'          => 'Size',
                'type'                => 'select',
                'validation'          => NULL,
                'position'            => '27',
                'is_required'         => '0',
                'is_unique'           => '0',
                'value_per_locale'    => '0',
                'value_per_channel'   => '0',
                'is_filterable'       => '1',
                'is_configurable'     => '1',
                'is_user_defined'     => '1',
                'is_visible_on_front' => '0',
                'use_in_flat'         => '1',
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => '0',
            ],
            [
                'id'                => '25',
                'code'                => 'brand',
                'name'          => 'Brand',
                'type'                => 'select',
                'validation'          => NULL,
                'position'            => '28',
                'is_required'         => '0',
                'is_unique'           => '0',
                'value_per_locale'    => '0',
                'value_per_channel'   => '0',
                'is_filterable'       => '1',
                'is_configurable'     => '0',
                'is_user_defined'     => '1',
                'is_visible_on_front' => '1',
                'use_in_flat'         => '1',
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => '0',
            ],
            [
                'id'                => '26',
                'code'                => 'guest_checkout',
                'name'          => 'Guest Checkout',
                'type'                => 'boolean',
                'validation'          => NULL,
                'position'            => '8',
                'is_required'         => '1',
                'is_unique'           => '0',
                'value_per_locale'    => '0',
                'value_per_channel'   => '0',
                'is_filterable'       => '0',
                'is_configurable'     => '0',
                'is_user_defined'     => '0',
                'is_visible_on_front' => '0',
                'use_in_flat'         => '1',
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => '0',
            ],
            [
                'id'                => '27',
                'code'                => 'product_number',
                'name'          => 'Product Number',
                'type'                => 'text',
                'validation'          => NULL,
                'position'            => '2',
                'is_required'         => '0',
                'is_unique'           => '1',
                'value_per_locale'    => '0',
                'value_per_channel'   => '0',
                'is_filterable'       => '0',
                'is_configurable'     => '0',
                'is_user_defined'     => '0',
                'is_visible_on_front' => '0',
                'use_in_flat'         => '1',
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => '0',
            ]
        ];

        foreach ($attributes as $key => $attribute) {
            Attribute::create($attribute);
        }


        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
}
